# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
default_platform(:ios)

platform :ios do
  desc "Build signed IPA"
  lane :build do
    setup_project
      match(
        git_basic_authorization: ENV['MATCH_GIT_BASIC_AUTHORIZATION'], 
        readonly: true,
        keychain_name: "ci_keychain",
        keychain_password: "password"
      )
      build_ios_app(
        workspace: "Runner.xcworkspace", 
        scheme: "Runner", 
        export_method: "app-store"
      )
  end
end

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    upload_to_testflight
  end
end

private_lane :setup_project do
  create_keychain(
    name: "ci_keychain",
    password: "password",
    default_keychain: true,
    unlock: true,
    timeout: 3600,
    lock_when_sleeps: false
  )
end